spring.application.name=ecommerce-modular-monolith


# Server Port
server.port=8080


# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecommerce_db


# Spring Security temporary user
spring.security.user.name=admin
spring.security.user.password=admin123